// Generated by Dagger (https://dagger.dev).
package com.uk.androidrecruitmentapp.data.network;

import com.uk.androidrecruitmentapp.data.util.RequestExecutor;

import dagger.internal.Factory;

@SuppressWarnings({
        "unchecked",
        "rawtypes"
})
public final class RequestExecutor_Factory implements Factory<RequestExecutor> {
    public static RequestExecutor_Factory create() {
        return InstanceHolder.INSTANCE;
    }

    public static RequestExecutor newInstance() {
        return new RequestExecutor();
    }

    @Override
    public RequestExecutor get() {
        return newInstance();
    }

    private static final class InstanceHolder {
        private static final RequestExecutor_Factory INSTANCE = new RequestExecutor_Factory();
    }
}
